//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.15 at 06:06:04 PM EET 
//


package JAXB;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tyontekija"
})
@XmlRootElement(name ="tyontekijat")
public class Tyontekijat {

    @XmlElement(required = true)
    protected List<Tyontekijat.Tyontekija> tyontekija;

   
    public List<Tyontekijat.Tyontekija> getTyontekija() {
        if (tyontekija == null) {
            tyontekija = new ArrayList<Tyontekijat.Tyontekija>();
        }
        return this.tyontekija;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sukunimi",
        "etunimi",
        "palkka",
        "osasto"
    })
    public static class Tyontekija {

        @XmlElement(required = true)
        protected String sukunimi;
        @XmlElement(required = true)
        protected List<Tyontekijat.Tyontekija.Etunimi> etunimi;
        protected BigDecimal palkka;
        protected Tyontekijat.Tyontekija.Osasto osasto;
        @XmlAttribute(name = "asema")
        protected String asema;
        @XmlAttribute(name = "id", required = true)
        @XmlSchemaType(name = "unsignedInt")
        protected long id;

                public String getSukunimi() {
            return sukunimi;
        }

        
        public void setSukunimi(String value) {
            this.sukunimi = value;
        }

       
        public List<Tyontekijat.Tyontekija.Etunimi> getEtunimi() {
            if (etunimi == null) {
                etunimi = new ArrayList<Tyontekijat.Tyontekija.Etunimi>();
            }
            return this.etunimi;
        }

        
        public BigDecimal getPalkka() {
            return palkka;
        }

        
        public void setPalkka(BigDecimal value) {
            this.palkka = value;
        }

        
        public Tyontekijat.Tyontekija.Osasto getOsasto() {
            return osasto;
        }

        
        public void setOsasto(Tyontekijat.Tyontekija.Osasto value) {
            this.osasto = value;
        }

       
        public String getAsema() {
            return asema;
        }

        
        public void setAsema(String value) {
            this.asema = value;
        }

        
        public long getId() {
            return id;
        }

       
        public void setId(long value) {
            this.id = value;
        }


       
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Etunimi {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "kutsuma")
            protected String kutsuma;

            public String getValue() {
                return value;
            }

            public void setValue(String value) {
                this.value = value;
            }

            public String getKutsuma() {
                return kutsuma;
            }

            public void setKutsuma(String value) {
                this.kutsuma = value;
            }

        }


       
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Osasto {

            @XmlAttribute(name = "nimi", required = true)
            protected String nimi;

           
            public String getNimi() {
                return nimi;
            }

            public void setNimi(String value) {
                this.nimi = value;
            }

        }

    }

}
