//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.19 at 10:09:26 PM EET 
//


package JAXBHUUTO;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "category",
    "summary",
    "expirationTime",
    "price",
    "deliveryMethods"
})
@XmlRootElement(name = "entry")
public class Entry {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected Entry.Category category;
    @XmlElement(required = true)
    protected String summary;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expirationTime;
    @XmlElement(required = true)
    protected Entry.Price price;
    @XmlElement(required = true)
    protected Entry.DeliveryMethods deliveryMethods;

        public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        this.title = value;
    }

    public Entry.Category getCategory() {
        return category;
    }
    public void setCategory(Entry.Category value) {
        this.category = value;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String value) {
        this.summary = value;
    }
    public XMLGregorianCalendar getExpirationTime() {
        return expirationTime;
    }
    public void setExpirationTime(XMLGregorianCalendar value) {
        this.expirationTime = value;
    }

    public Entry.Price getPrice() {
        return price;
    }

    public void setPrice(Entry.Price value) {
        this.price = value;
    }

    public Entry.DeliveryMethods getDeliveryMethods() {
        return deliveryMethods;
    }

    public void setDeliveryMethods(Entry.DeliveryMethods value) {
        this.deliveryMethods = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Category {

        @XmlAttribute(name = "scheme", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String scheme;

        public String getScheme() {
            return scheme;
        }

        public void setScheme(String value) {
            this.scheme = value;
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deliveryMethod"
    })
    public static class DeliveryMethods {

        @XmlElement(required = true)
        protected List<Entry.DeliveryMethods.DeliveryMethod> deliveryMethod;

        public List<Entry.DeliveryMethods.DeliveryMethod> getDeliveryMethod() {
            if (deliveryMethod == null) {
                deliveryMethod = new ArrayList<Entry.DeliveryMethods.DeliveryMethod>();
            }
            return this.deliveryMethod;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DeliveryMethod {

            @XmlAttribute(name = "type", required = true)
            protected String type;

            public String getType() {
                return type;
            }
            public void setType(String value) {
                this.type = value;
            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "startingPrice",
        "minimumIncrease",
        "buyNowPrice"
    })
    public static class Price {

        @XmlElement(required = true)
        protected Entry.Price.StartingPrice startingPrice;
        protected Entry.Price.MinimumIncrease minimumIncrease;
        protected Entry.Price.BuyNowPrice buyNowPrice;

        /**
         * Gets the value of the startingPrice property.
         * 
         * @return
         *     possible object is
         *     {@link Entry.Price.StartingPrice }
         *     
         */
        public Entry.Price.StartingPrice getStartingPrice() {
            return startingPrice;
        }

        /**
         * Sets the value of the startingPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link Entry.Price.StartingPrice }
         *     
         */
        public void setStartingPrice(Entry.Price.StartingPrice value) {
            this.startingPrice = value;
        }

        public Entry.Price.MinimumIncrease getMinimumIncrease() {
            return minimumIncrease;
        }
        public void setMinimumIncrease(Entry.Price.MinimumIncrease value) {
            this.minimumIncrease = value;
        }
        public Entry.Price.BuyNowPrice getBuyNowPrice() {
            return buyNowPrice;
        }

        public void setBuyNowPrice(Entry.Price.BuyNowPrice value) {
            this.buyNowPrice = value;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class BuyNowPrice {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute(name = "currency")
            protected String currency;

            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
         *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class MinimumIncrease {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute(name = "currency")
            protected String currency;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>decimal">
         *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class StartingPrice {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute(name = "currency")
            protected String currency;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

        }

    }

}
